version: "3.7"
services:
  liferay-tomcat:
    image: liferay-tomcat
    build: liferay-tomcat
    container_name: liferay-tomcat
    depends_on:
      - mysql
    networks: 
      - network-liferay-tomcat
    ports: 
      - 8081:8080
      - 127.0.0.1:11311:11311
    volumes:
      - volume-liferay-tomcat-data:/opt/liferay/data
      - volume-liferay-tomcat-work:/opt/liferay/work
  mysql:
    image: mysql
    build: mysql
    container_name: mysql
    networks:
      - network-liferay-tomcat
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - volume-mysql:/var/lib/mysql
networks:
  network-liferay-tomcat:
    name: network-liferay-tomcat
volumes:
  volume-liferay-tomcat-data:
  volume-liferay-tomcat-work:
  volume-mysql:
