version: "3.7"
services:
  apacheds:
    build: apacheds
    container_name: apacheds
    networks: 
      - network-liferay-tomcat
    ports: 
      - 10389:10389
    volumes:
      - volume-apacheds:/opt/liferay/apacheds-2.0.0.AM25/instances
  elasticsearch:
    build: elasticsearch
    container_name: elasticsearch
    environment: 
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    networks:
      - network-liferay-tomcat
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - volume-elasticsearch:/usr/share/elasticsearch/data
  haproxy:
    build: haproxy
    container_name: haproxy
    networks:
      - network-liferay-tomcat
    ports:
      - 80:80
      - 9999:9999
  liferay-staging:
    build: liferay-staging
    container_name: liferay-staging
    networks: 
      - network-liferay-tomcat
    ports: 
      - 8085:8080
      - 127.0.0.1:51311:11311
    volumes:
      - volume-liferay-staging-data:/opt/liferay/data
      - volume-liferay-staging-work:/opt/liferay/work
  liferay-tomcat-1:
    build: liferay-tomcat
    container_name: liferay-tomcat-1
    depends_on:
#      - apacheds
#      - elasticsearch
      - mysql
    networks: 
      - network-liferay-tomcat
    ports: 
      - 8081:8080
      - 127.0.0.1:11311:11311
    volumes:
      - volume-liferay-tomcat-data:/opt/liferay/data
      - volume-liferay-tomcat-1-work:/opt/liferay/work
#  liferay-tomcat-2:
#    build: liferay-tomcat
#    container_name: liferay-tomcat-2
#    depends_on:
#      - mysql
#    networks: 
#      - network-liferay-tomcat
#    ports: 
#      - 8082:8080
#      - 127.0.0.1:21311:11311
#    volumes:
#      - volume-liferay-tomcat-data:/opt/liferay/data
#      - volume-liferay-tomcat-2-work:/opt/liferay/work
  mysql:
    build: mysql
    container_name: mysql
    networks:
      - network-liferay-tomcat
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - volume-mysql:/var/lib/mysql
networks:
  network-liferay-tomcat:
    name: network-liferay-tomcat
volumes:
  volume-apacheds:
  volume-elasticsearch:
  volume-liferay-staging-data:
  volume-liferay-staging-work:
  volume-liferay-tomcat-data:
  volume-liferay-tomcat-1-work:
  volume-liferay-tomcat-2-work:
  volume-mysql:
